# Generated by Django 4.2 on 2024-10-06 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(default=1, max_length=19),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='fullname',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
