# Generated by Django 4.2 on 2024-10-08 10:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0003_contact_alter_userprofile_fullname_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_system', models.CharField(choices=[('process_48', 'Bitcoin'), ('process_1000', 'USDT ERC20'), ('process_eth', 'Ethereum')], max_length=20)),
                ('crypto_amount', models.DecimalField(decimal_places=4, max_digits=10)),
                ('staking_plan', models.IntegerField(choices=[(1, 'LITE'), (2, 'STANDARD'), (3, 'PREMIUM'), (4, 'DIAMOND')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
