# Generated by Django 4.2 on 2024-10-08 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_deposit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='payment_system',
            field=models.CharField(choices=[('Bitcoin', 'Bitcoin'), ('USDT_ERC20', 'USDT ERC20'), ('Ethereum', 'Ethereum')], max_length=20),
        ),
    ]
