# Generated by Django 4.2 on 2024-10-08 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_deposit_payment_system'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(choices=[('Bitcoin', 'Bitcoin'), ('USDT_ERC20', 'USDT ERC20'), ('Ethereum', 'Ethereum')], max_length=20, unique=True)),
                ('wallet_address', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
