# Generated by Django 4.2 on 2024-10-08 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_wallet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='staking_plan',
            field=models.IntegerField(choices=[(1, 'LITE 150%'), (2, 'STANDARD 200%'), (3, 'PREMIUM 250%'), (4, 'DIAMOND 250%')]),
        ),
    ]
