# Generated by Django 4.2 on 2024-10-08 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_deposit_staking_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='payment_system',
            field=models.CharField(choices=[('Bitcoin', 'Bitcoin'), ('Litecoin', 'Litecoin'), ('Ethereum', 'Ethereum')], max_length=20),
        ),
    ]
