# Generated by Django 4.2 on 2024-10-08 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_deposit_payment_system'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='payment_method',
            field=models.CharField(choices=[('Bitcoin', 'Bitcoin'), ('Litecoin', 'Litecoin'), ('Ethereum', 'Ethereum')], max_length=20, unique=True),
        ),
    ]
