# Generated by Django 4.2 on 2024-10-13 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_withdraw_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='withdraw',
            name='date_created',
            field=models.DateTimeField(),
        ),
    ]
