# Generated by Django 4.2 on 2024-10-13 13:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_deposit_created_at_alter_withdraw_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='withdraw',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
