# Generated by Django 4.2 on 2024-11-06 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_investmentplan_stake'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='staking_plan',
            field=models.IntegerField(choices=[(1, 'LITE 50%'), (2, 'STANDARD 100%'), (3, 'PREMIUM 150%'), (4, 'DIAMOND 200%')]),
        ),
    ]
