# Generated by Django 4.2 on 2024-11-06 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_deposit_staking_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investmentplan',
            name='daily_percentage',
            field=models.IntegerField(),
        ),
    ]
