# Generated by Django 5.2.7 on 2025-10-11 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_investmentplan_daily_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='last_earnings_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='staking_plan',
            field=models.IntegerField(choices=[(1, 'LITE'), (2, 'STANDARD'), (3, 'PREMIUM'), (4, 'DIAMOND')]),
        ),
        migrations.AlterField(
            model_name='financialstatistic',
            name='statistic_type',
            field=models.CharField(choices=[('total_deposit', 'Total Deposit'), ('total_withdrawal', 'Total Withdrawal'), ('total_earned', 'Total Earned'), ('active_deposit', 'Active Deposit'), ('active_plan', 'Active Plan')], max_length=30),
        ),
    ]
